### ISSUE TITLE
Ecrire executable pour lander les manips (ctew1_analyser/ctew1_handler par exemple)

### ISSUE THREAD

**Issue by jihanesayadi** [eost/pyCTEW1#5]

**Comment by mbdb** [comment]
Ecriture d'executables pour une utilisation plus saine:
ctew1_analyser
ctew1_handler
par exemple

les scripts python à modifier sont à proscrire...

**Comment by mbdb** [comment]
ctew1_H_analyser
ctew1_V_analyser
ctew1_shaker
